const mix = require('laravel-mix');

mix

    .scripts('resources/views/Admin/assets/js/app.min.js', 'public/admin/assets/js/app.min.js')
    .scripts('resources/views/Admin/assets/js/vendor.min.js', 'public/admin/assets/js/vendor.min.js')
    .scripts('resources/views/Admin/assets/js/custom.js', 'public/admin/assets/js/custom.js')
    // plugins
    .scripts('node_modules/parsleyjs/dist/parsley.min.js', 'public/admin/assets/libs/parsley.min.js')
    .scripts('node_modules/@fancyapps/ui/dist/fancybox.umd.js', 'public/admin/assets/libs/fancybox.js')
    .scripts('node_modules/selectize/dist/js/selectize.min.js', 'public/admin/assets/libs/selectize.min.js')
    .scripts('node_modules/mohithg-switchery/dist/switchery.min.js', 'public/admin/assets/libs/switchery.min.js')
    .scripts('node_modules/multiselect/js/jquery.multi-select.js', 'public/admin/assets/libs/jquery.multi-select.js')
    .scripts('node_modules/select2/dist/js/select2.min.js', 'public/admin/assets/libs/select2.min.js')
    .scripts('node_modules/jquery-mockjax/dist/jquery.mockjax.min.js', 'public/admin/assets/libs/jquery.mockjax.min.js')
    .scripts('node_modules/devbridge-autocomplete/dist/jquery.autocomplete.min.js', 'public/admin/assets/libs/jquery.autocomplete.min.js')
    .scripts('node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js', 'public/admin/assets/libs/jquery.bootstrap-touchspin.min.js')
    .scripts('node_modules/bootstrap-maxlength/dist/bootstrap-maxlength.min.js', 'public/admin/assets/libs/bootstrap-maxlength.min.js')
    .scripts('node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js', 'public/admin/assets/libs/bootstrap-datepicker.min.js')
    .scripts('node_modules/clockpicker/dist/bootstrap-clockpicker.min.js', 'public/admin/assets/libs/bootstrap-clockpicker.min.js')
    .scripts('node_modules/spectrum-colorpicker2/dist/spectrum.min.js', 'public/admin/assets/libs/spectrum.min.js')
    .scripts('node_modules/flatpickr/dist/flatpickr.min.js', 'public/admin/assets/libs/flatpickr.min.js')
    .scripts('node_modules/jquery-mask-plugin/dist/jquery.mask.min.js', 'public/admin/assets/libs/jquery.mask.min.js')
    .scripts('node_modules/autonumeric/dist/autoNumeric.min.js', 'public/admin/assets/libs/autoNumeric.min.js')
    .scripts('node_modules/dropzone/dist/min/dropzone.min.js', 'public/admin/assets/libs/dropzone.min.js')
    .scripts('node_modules/dropify/dist/js/dropify.min.js', 'public/admin/assets/libs/dropify.min.js')
    .scripts('resources/views/Admin/assets/js/libs/ckeditor.js', 'public/admin/assets/libs/ckeditor.js')
    .scripts('node_modules/bootstrap-table/dist/bootstrap-table.min.js', 'public/admin/assets/libs/bootstrap-table.min.js')
    .scripts('node_modules/jquery-tabledit/jquery.tabledit.min.js', 'public/admin/assets/libs/jquery.tabledit.min.js')
    .scripts('node_modules/sweetalert2/dist/sweetalert2.all.min.js', 'public/admin/assets/libs/sweetalert2.all.min.js')
    .scripts('node_modules/jquery-toast-plugin/dist/jquery.toast.min.js', 'public/admin/assets/libs/jquery.toast.min.js')
    .scripts('resources/views/Admin/assets/js/libs/jquery.sortable.min.js', 'public/admin/assets/libs/jquery.sortable.min.js')
    .scripts('node_modules/tippy.js/dist/tippy.all.min.js', 'public/admin/assets/libs/tippy.all.min.js')
    .scripts('node_modules/cropper/dist/cropper.min.js', 'public/admin/assets/libs/cropper.min.js')
    // Pages
    .scripts('resources/views/Admin/assets/js/pages/form-validation.init.js', 'public/admin/assets/js/pages/form-validation.init.js')
    .scripts('resources/views/Admin/assets/js/pages/form-advanced.init.js', 'public/admin/assets/js/pages/form-advanced.init.js')
    .scripts('resources/views/Admin/assets/js/pages/form-pickers.init.js', 'public/admin/assets/js/pages/form-pickers.init.js')
    .scripts('resources/views/Admin/assets/js/pages/form-masks.init.js', 'public/admin/assets/js/pages/form-masks.init.js')
    .scripts('resources/views/Admin/assets/js/pages/form-fileuploads.init.js', 'public/admin/assets/js/pages/form-fileuploads.init.js')
    .scripts('resources/views/Admin/assets/js/pages/add-product.init.js', 'public/admin/assets/js/pages/add-product.init.js')
    .scripts('resources/views/Admin/assets/js/pages/ckeditor.init.js', 'public/admin/assets/js/pages/ckeditor.init.js')
    .scripts('resources/views/Admin/assets/js/pages/bootstrap-tables.init.js', 'public/admin/assets/js/pages/bootstrap-tables.init.js')
    .scripts('resources/views/Admin/assets/js/pages/tabledit.init.js', 'public/admin/assets/js/pages/tabledit.init.js')
    .scripts('resources/views/Admin/assets/js/pages/toastr.init.js', 'public/admin/assets/js/pages/toastr.init.js')
    .scripts('resources/views/Admin/assets/js/pages/materialdesign.init.js', 'public/admin/assets/js/pages/materialdesign.init.js')
    .scripts('resources/views/Admin/assets/js/pages/form-imagecrop.init.js', 'public/admin/assets/js/pages/form-imagecrop.init.js')

    //CSS
    .styles('resources/views/Admin/assets/css/config/bootstrap.min.css', 'public/admin/assets/css/config/bootstrap.min.css')
    .styles('resources/views/Admin/assets/css/config/app.min.css', 'public/admin/assets/css/config/app.min.css')
    .styles('resources/views/Admin/assets/css/config/bootstrap-dark.min.css', 'public/admin/assets/css/config/bootstrap-dark.min.css')
    .styles('resources/views/Admin/assets/css/config/app-dark.min.css', 'public/admin/assets/css/config/app-dark.min.css')
    .styles('resources/views/Admin/assets/css/icons.min.css', 'public/admin/assets/css/icons.min.css')
    .styles('resources/views/Admin/assets/css/custom.css', 'public/admin/assets/css/custom.css')

    //CSS Client
    .styles('resources/client/assets/css/global.css', 'public/client/assets/css/global.css')
    .styles('resources/client/assets/css/home.css', 'public/client/assets/css/home.css')
    .styles('resources/client/assets/css/login.css', 'public/client/assets/css/login.css')
    .styles('resources/client/assets/css/register.css', 'public/client/assets/css/register.css')
    .styles('resources/client/assets/css/projects.css', 'public/client/assets/css/projects.css')
    .styles('resources/client/assets/css/project.css', 'public/client/assets/css/project.css')
    .styles('resources/client/assets/css/dashboard.css', 'public/client/assets/css/dashboard.css')
    .styles('resources/client/assets/css/blogs.css', 'public/client/assets/css/blogs.css')
    .styles('resources/client/assets/css/blog.css', 'public/client/assets/css/blog.css')

    //Plugins
    .styles('node_modules/mohithg-switchery/dist/switchery.min.css', 'public/admin/assets/libs/switchery.min.css')
    .styles('node_modules/@fancyapps/ui/dist/fancybox.css', 'public/admin/assets/libs/fancybox.css')
    .styles('node_modules/multiselect/css/multi-select.css', 'public/admin/assets/libs/multi-select.css')
    .styles('node_modules/select2/dist/css/select2.min.css', 'public/admin/assets/libs/select2.min.css')
    .styles('node_modules/selectize/dist/css/selectize.bootstrap3.css', 'public/admin/assets/libs/selectize.bootstrap3.css')
    .styles('node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css', 'public/admin/assets/libs/jquery.bootstrap-touchspin.min.css')
    .styles('node_modules/spectrum-colorpicker2/dist/spectrum.min.css', 'public/admin/assets/libs/spectrum.min.css')
    .styles('node_modules/flatpickr/dist/flatpickr.min.css', 'public/admin/assets/libs/flatpickr.min.css')
    .styles('node_modules/clockpicker/dist/bootstrap-clockpicker.min.css', 'public/admin/assets/libs/bootstrap-clockpicker.min.css')
    .styles('node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css', 'public/admin/assets/libs/bootstrap-datepicker.min.css')
    .styles('node_modules/dropzone/dist/min/dropzone.min.css', 'public/admin/assets/libs/dropzone.min.css')
    .styles('node_modules/quill/dist/quill.core.css', 'public/admin/assets/libs/quill.core.css')
    .styles('node_modules/quill/dist/quill.snow.css', 'public/admin/assets/libs/quill.snow.css')
    .styles('node_modules/dropify/dist/css/dropify.min.css', 'public/admin/assets/libs/dropify.min.css')
    .styles('node_modules/bootstrap-table/dist/bootstrap-table.min.css', 'public/admin/assets/libs/bootstrap-table.min.css')
    .styles('node_modules/sweetalert2/dist/sweetalert2.min.css', 'public/admin/assets/libs/sweetalert2.min.css')
    .styles('node_modules/jquery-toast-plugin/dist/jquery.toast.min.css', 'public/admin/assets/libs/jquery.toast.min.css')
    .styles('node_modules/cropper/dist/cropper.min.css', 'public/admin/assets/libs/cropper.min.css')

    //CONFIG
    .autoload({
        'jquery': ['$', 'window.jQuery', 'jQuery']
    })
    .copyDirectory('resources/views/Admin/assets/fonts', 'public/admin/assets/fonts')
    .copyDirectory('resources/views/Admin/assets/images', 'public/admin/assets/images')
    .copyDirectory('node_modules/@ckeditor/ckeditor5-build-classic/build/translations', 'public/admin/assets/libs/translations')
    .copyDirectory('node_modules/parsleyjs/dist/i18n', 'public/admin/assets/libs/i18n')
    .version()
